version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: agent-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker_env/nginx:/etc/nginx/conf.d
      - ./docker_env/nginx/html/dist:/usr/share/nginx/html
      - ./docker_env/nginx/50x.html:/usr/share/nginx/html/50x.html
      - ./docker_env/admin/static/images:/usr/share/nginx/html/static/images:ro

    environment:
      - TZ=Asia/Shanghai  # ✅ 设置时区为东八区
    restart: unless-stopped
    networks:
      - anime-network

  qdrant:  # 向量数据库
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./docker_env/qdrant/data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_LISTEN_ADDR=0.0.0.0:6333
      - QDRANT__SERVICE__GRPC_LISTEN_ADDR=0.0.0.0:6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - anime-network

  langchain_agent:
    env_file: .env
    build:
      context: ./langchain_agent
      dockerfile: Dockerfile
    container_name: langchain_agent
    volumes:
      - ./langchain_agent:/app  # 挂载本地项目目录到容器的 /app
      - ./langchain_agent/models_cache:/app/models_cache  # 挂载模型缓存目录
    ports:
      - "8000:8000" 
    environment:
      - HF_HOME=/app/models_cache
      - HF_DATASETS_CACHE=/app/models_cache
      - TOKENIZERS_PARALLELISM=false
    networks:
      - anime-network
    restart: unless-stopped

networks:
  anime-network:
    driver: bridge